"""init schema

Revision ID: 004fe126d71c
Revises: 
Create Date: 2026-08-05 21:44:47.716397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
import sqlmodel
from sqlalchemy.dialects import postgresql

revision: str = '004fe126d71c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyword',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keyword_text'), 'keyword', ['text'], unique=True)
    op.create_table('setting',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('sourcehealth',
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('alert_open', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('source')
    )
    op.create_table('hotspot',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('is_real', sa.Boolean(), nullable=False),
    sa.Column('relevance', sa.Integer(), nullable=False),
    sa.Column('relevance_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('keyword_mentioned', sa.Boolean(), nullable=True),
    sa.Column('importance', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ai_reviewed', sa.Boolean(), nullable=False),
    sa.Column('hot_score', sa.Float(), nullable=False),
    sa.Column('importance_rank', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('retweet_count', sa.Integer(), nullable=True),
    sa.Column('reply_count', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('quote_count', sa.Integer(), nullable=True),
    sa.Column('danmaku_count', sa.Integer(), nullable=True),
    sa.Column('author_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('author_avatar', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('author_verified', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('keyword_id', sa.Uuid(), nullable=True),
    sa.Column('raw_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['keyword_id'], ['keyword.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url', 'source', name='uq_hotspot_url_source')
    )
    op.create_index(op.f('ix_hotspot_created_at'), 'hotspot', ['created_at'], unique=False)
    op.create_index('ix_hotspot_feed', 'hotspot', ['created_at', 'importance_rank', 'hot_score'], unique=False)
    op.create_index('ix_hotspot_published_at', 'hotspot', ['published_at'], unique=False)
    op.create_index(op.f('ix_hotspot_source'), 'hotspot', ['source'], unique=False)
    op.create_table('notification',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('hotspot_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['hotspot_id'], ['hotspot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_created_at'), 'notification', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_created_at'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_hotspot_source'), table_name='hotspot')
    op.drop_index('ix_hotspot_published_at', table_name='hotspot')
    op.drop_index('ix_hotspot_feed', table_name='hotspot')
    op.drop_index(op.f('ix_hotspot_created_at'), table_name='hotspot')
    op.drop_table('hotspot')
    op.drop_table('sourcehealth')
    op.drop_table('setting')
    op.drop_index(op.f('ix_keyword_text'), table_name='keyword')
    op.drop_table('keyword')
    # ### end Alembic commands ###
